// svelte/remote/src/routes/Counter.svelte
<script lang="ts">
	let count = $state(0);
</script>

<button class="counter-btn" onclick={() => count++}>
	Remote counter: {count}
</button>

<style>
	.counter-btn {
		margin-top: 11px;
		background-color: #f6b352;
		border: none;
		border-radius: 0.19rem;
		font-weight: 700;
		font-size: 12px;
		padding: 0.375rem 1.125rem;
		color: #181818;
		cursor: pointer;
	}
</style>

// nuxt/remote/app/components/counter.vue
<script setup lang="ts">
import { useCounterStore } from "../stores/counter";
const { $pinia } = useNuxtApp();
const store = useCounterStore($pinia);
const { count } = storeToRefs(store);
</script>

<template>
  <button
    style="
      border: 0 solid #e2e8f0;
      margin-top: 10px;
      background-color: rgb(246, 179, 82);
      border-radius: 0.25rem;
      font-weight: 700;
      padding: 0.5rem 1rem 0.5rem 1rem;
      color: rgb(24, 24, 24);
    "
    @click="store.increment"
  >
    Remote counter: {{ count }}
  </button>
</template>

<style scoped />
