// vinext/host/app/counter.tsx
"use client";

import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);

  return (
    <button
      style={{
        border: "2px solid rgb(246, 179, 82)",
        marginTop: "10px",
        backgroundColor: "rgb(246, 179, 82)",
        borderRadius: ".25rem",
        fontWeight: "700",
        padding: ".3rem .75rem",
        fontSize: "14px",
        color: "rgb(24, 24, 24)",
        cursor: "pointer",
      }}
      onClick={() => setCount((currentCount) => currentCount + 1)}
    >
      Host counter: {count}
    </button>
  );
}

// nuxt/host/app/components/counter.vue
<script setup lang="ts">
import { useCounterStore } from "../stores/counter";
const store = useCounterStore();
const { count } = storeToRefs(store);
</script>

<template>
  <button class="counter" @click="store.increment">Host counter: {{ count }}</button>
</template>

<style scoped>
.counter {
  border: 0 solid #e2e8f0;
  margin-top: 10px;
  background-color: rgb(246, 179, 82);
  border-radius: 0.25rem;
  font-weight: 700;
  padding: 0.5rem 1rem 0.5rem 1rem;
  color: rgb(24, 24, 24);
}
</style>
